=== devilolo/tuxlgame/Service/CabinetInfirmierServer/src/java/fr/ujf_grenoble/l3miage/medical/resources/cabinet.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vds="http://www.ujf-grenoble.fr/l3miage/medical"
           targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
           elementFormDefault="qualified">
           
    
    <xs:element name="cabinet" type="vds:Cabinet"/>
    <!-- le cabinet  avec nom , adresse , infirmiers , patients -->
    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="adresse" type="vds:Adresse"/>
            <xs:element name="infirmiers" type="vds:Infirmiers" minOccurs="0" maxOccurs="unbounded"/> 
            <xs:element name="patients" type="vds:Patients"/>
        </xs:sequence>
    </xs:complexType>
    
    <!--l'adresse avecétage, numéro, rue, ville , codePostal   -->
    <xs:complexType name="Adresse">
        <xs:sequence>
            <xs:element name="étage" type="xs:string" minOccurs="0"/>
            <xs:element name="numéro" type="xs:int" minOccurs="0"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="ville" type="xs:string"/>             
            <xs:element name="codePostal" type="vds:CodePostal"/>
        </xs:sequence>
    </xs:complexType>
    
    <!--simple type de code postaL sans E ici attention  --> 
    
    <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:integer">
            <xs:pattern value="(\s*)[0-9][0-9][0-9][0-9][0-9](\s*)" />
        </xs:restriction>
    </xs:simpleType>
    
    <!--les infirmiers avec infirmier   -->
        
    <xs:complexType name="Infirmiers">
        <xs:sequence>
            <xs:element name="infirmier" type="vds:Infirmier" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence> 
    </xs:complexType>
    
    <!--infirmier nom, prénom, photo   -->
        
    <xs:complexType name="Infirmier">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prénom" type="xs:string"/>
            <xs:element name="photo" type="vds:Photo"/>
        </xs:sequence>
        <xs:attribute name="id" type="vds:Id"/>
    </xs:complexType>
    
    <xs:simpleType name="Id">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\s*([0-9][0-9][0-9])\s*" />
        </xs:restriction>
    </xs:simpleType>
    
    
    <!-- \D*[.](png|jpg) -->
    
    <xs:simpleType name="Photo">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\s*).*(png|jpg|jpeg|gif)(\s*)" />
        </xs:restriction>
    </xs:simpleType>
     
     
     
     
    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" type="vds:Patient" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <!-- patient avec nom prénom sexe naissance numéro (de type numéro en dessous !!) adresse visite -->
    <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prénom" type="xs:string"/>
            <xs:element name="sexe" type="vds:Sexe"/> 
            <xs:element name="naissance" type="vds:Date"/>
            <xs:element name="numéro" type="vds:Numéro" />
            <xs:element name="adresse" type="vds:Adresse"/>
            <xs:element name="visite" type="vds:Visite" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="Date">
        <xs:restriction base="xs:date">
            <xs:pattern value="[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" />
        </xs:restriction>
    </xs:simpleType> 
    
    
    
    <!-- sexe M ou F -->
    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:pattern value="\s*(F|M)\s*" />
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:simpleType name="Numéro">
        <xs:restriction base="xs:string">
            <xs:pattern value="([1-4]|[7-8])([0-9]{2})(0[1-9]|1[1-2]|62|63)(((([0-1][1-9]|10)|2A|2B|2[1-9]|[3-9][0-9])([0-9][0-8][1-9]|[0-9][1-8][0-9]|[1-9][0-9]0{2}))|((9[7-8][0-9])([0-8][1-9]|[1-9]0))|(9{2}([0-9][0-8][1-9]|[0-9][1-8][0-9]|[1-9][0-9]0{2})))([0-9][0-8][1-9]|[0-9][1-9][0-9]|[1-9]0{2})(0[1-9]|[1-8][0-9]|9[0-7])" />
        </xs:restriction>
    </xs:simpleType> 
  
 

    
    <xs:complexType name="Visite">
        <xs:sequence>
            <xs:element name="acte" type="vds:Acte" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="date" type="vds:Date"/>
        <xs:attribute name="intervenant" type="vds:Id"/>
    </xs:complexType>
   
    <!-- Ici faire qu'on peut avoir un intervenant vide      ((\s*)[0-9]{3}*(\s*))* -->
 
    
    <xs:complexType name="Acte">
        <xs:sequence>
            <xs:element name="interieurActe" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name ="id" type ="xs:int"/>        
    </xs:complexType>
   
</xs:schema>

=== devilolo/tuxlgame/Service/CabinetInfirmierServer/build/web/WEB-INF/classes/fr/ujf_grenoble/l3miage/medical/resources/cabinet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<vds:cabinet
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:vds='http://www.ujf-grenoble.fr/l3miage/medical'
    xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/medical ../XSD/cabinet.xsd'>
    
    <vds:nom>Soins à Grenoble</vds:nom>
    <vds:adresse>
        <vds:numéro>60</vds:numéro>
        <vds:rue>rue de la Chimie</vds:rue>
        <vds:ville>Grenoble</vds:ville>
        <vds:codePostal>38041</vds:codePostal>
    </vds:adresse>
    <vds:infirmiers>
        <vds:infirmier id="001">
            <vds:nom>Fréchie</vds:nom>
            <vds:prénom>Sarah</vds:prénom> 
            <vds:photo>sarah.png</vds:photo>
        </vds:infirmier>
        <vds:infirmier id="002">
            <vds:nom>Stické</vds:nom>
            <vds:prénom>Sophie</vds:prénom> 
            <vds:photo>sophie.png</vds:photo>
        </vds:infirmier>
        <vds:infirmier id="003">
            <vds:nom>Ochon</vds:nom>
            <vds:prénom>Paul</vds:prénom> 
            <vds:photo>paul.png</vds:photo>
        </vds:infirmier>        
    </vds:infirmiers>
    <vds:patients>
        <vds:patient>
            <!-- Homme, née en aout 98 en France,
            à Marseille (n°55 en bouche du rhône)
            458e naissance
            -->
            <vds:nom>Alécole</vds:nom>
            <vds:prénom>Yvon</vds:prénom>
            <vds:sexe>M</vds:sexe>
            <vds:naissance>1998-08-02</vds:naissance>
            <vds:numéro>198082205545852</vds:numéro>
            <vds:adresse>
                <vds:étage>6</vds:étage>
                <vds:numéro>50</vds:numéro>
                <vds:rue>avenue Félix Viallet</vds:rue>
                <vds:ville>Grenoble</vds:ville>
                <vds:codePostal>38031</vds:codePostal>
            </vds:adresse>
            <vds:visite date="2015-12-08" intervenant="001" >
                <vds:acte id="109"></vds:acte>
            </vds:visite>
        </vds:patient>
        <vds:patient>
            <vds:nom>Orouge</vds:nom>
            <vds:prénom>Elvire</vds:prénom>
            <vds:sexe>F</vds:sexe>
            <vds:naissance>1982-03-08</vds:naissance>
            <vds:numéro>282036902305218</vds:numéro>
            <vds:adresse>
                <vds:rue>Rond-Point de la Croix de Vie</vds:rue>
                <vds:ville>La Tronche</vds:ville>
                <vds:codePostal>38700</vds:codePostal>
            </vds:adresse>
            <vds:visite date="2015-12-08"  >
                <vds:acte id="300"></vds:acte>
            </vds:visite>
        </vds:patient>
        <vds:patient>
            <vds:nom>Pien</vds:nom>
            <vds:prénom>Oscare</vds:prénom>
            <vds:sexe>M</vds:sexe>
            <vds:naissance>1975-03-25</vds:naissance>
            <vds:numéro>175037306569252</vds:numéro>
            <vds:adresse>
                <vds:rue>rue Casimir Brenier</vds:rue>
                <vds:ville>Grenoble</vds:ville>
                <vds:codePostal>38000</vds:codePostal>
            </vds:adresse>
            <vds:visite date="2015-12-08"  >
                <vds:acte id="101"></vds:acte>
                <vds:acte id="105"></vds:acte>
            </vds:visite>
        </vds:patient>
        <vds:patient>
            <vds:nom>Kapoëtla</vds:nom>
            <vds:prénom>Xavier</vds:prénom>
            <vds:sexe>M</vds:sexe>
            <vds:naissance>2011-08-02</vds:naissance>
            <vds:numéro>111083306303521</vds:numéro>
            <vds:adresse>
                <vds:numéro>25</vds:numéro>
                <vds:rue>rue des Martyrs</vds:rue>
                <vds:ville>Grenoble</vds:ville>
                <vds:codePostal>38042</vds:codePostal>
            </vds:adresse>
            <vds:visite date="2015-12-08" >
                <vds:acte id="111"></vds:acte>
            </vds:visite>
        </vds:patient>
    </vds:patients>
</vds:cabinet>
