=== devilolo/tuxlgame/TuxLetterGame_template/build/classes/xml/plateau.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://myGame/tux"
           targetNamespace="http://myGame/tux"
           elementFormDefault="qualified">
    <xs:element name="plateau" type="Plateau" />

    <xs:complexType name="Plateau">
        <xs:sequence>
            <xs:element name="dimensions" type="Dimensions">
            </xs:element>
            <xs:element name="mapping" type="Mapping">                
            </xs:element>
            <xs:element name="pion" type="xs:string">                
            </xs:element>
        </xs:sequence>
    </xs:complexType>  
    
    <xs:complexType name="Dimensions">
        <xs:sequence>
            <xs:element name="height" type="xs:int">
            </xs:element>
            <xs:element name="width" type="xs:int">                
            </xs:element>
            <xs:element name="depth" type="xs:int">                
            </xs:element>
        </xs:sequence>          
    </xs:complexType>                      
        
    <xs:complexType name="Mapping">
        <xs:sequence>
            <xs:element name="textureBottom" type="xs:string">
            </xs:element>
            <xs:element name="textureEast" type="xs:string">                
            </xs:element>
            <xs:element name="textureWest" type="xs:string">                
            </xs:element>
            <xs:element name="textureNorth" type="xs:string">                
            </xs:element>
        </xs:sequence>          
    </xs:complexType>
</xs:schema>

=== devilolo/tuxlgame/TuxLetterGame_template/build/classes/dicoxml/plateau.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<plateau
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://lemaire/tux'
    xsi:schemaLocation='http://lemaire/tux file:/home/l/lemairlo/LangagePourLeWeb/TLG/xsd/plateau.xsd'>
    <dimensions>
        <height>
            100
        </height>
        <width>
            40
        </width>
        <depth>
            50
        </depth>
    </dimensions>
    <mapping>
        <textureBottom>
            textures/floor/grass2.png
        </textureBottom>
        <textureEast>
            textures/skybox/interstellar/east.png
        </textureEast>
        <textureWest>
            textures/skybox/interstellar/west.png
        </textureWest>
        <textureNorth>
            textures/skybox/interstellar/north.png
        </textureNorth>
    </mapping>
    <pion>
        une url
    </pion>

</plateau>
